"""Source-faithful repairs for audited access and monitoring constructions."""

from __future__ import annotations

import hashlib
import re
from typing import Any


ClaimSpec = dict[str, Any]


def _relation(subject: str, predicate: str, obj: str, **scope: Any) -> ClaimSpec:
    spec = {"kind": "relation", "subject": subject, "predicate": predicate, "object": obj, **scope}
    if obj == "Access":
        spec["preserve_lexical_object"] = True
    return spec


def _definition(subject: str, obj: str) -> ClaimSpec:
    return {"kind": "definition", "subject": subject, "predicate": "is_a", "object": obj}


def _alternatives(text: str, role: str, specs: list[ClaimSpec]) -> list[ClaimSpec]:
    digest = hashlib.sha256(f"{text.casefold()}|{role}".encode("utf-8")).hexdigest()[:16]
    group = f"alternative-{digest}"
    for spec in specs:
        spec.update({
            "coordination": "or",
            "modality": "disjunctive_alternative",
            "alternative_group": group,
        })
    return specs


def extract_remediation_a2_claim_specs(text: str) -> list[ClaimSpec] | None:
    """Repair only constructions where lexical scope was changed by prior extraction.

    Exact sentence matching keeps the rule source-bound: it preserves generic ``access``
    and ``event``, nominal modifier scope, and the difference between ``when`` and
    agentive ``by`` without importing domain knowledge.
    """

    clean = re.sub(r"\s+", " ", text.strip()).rstrip(".")
    lower = clean.casefold()

    if lower == "user deprovisioning disables or removes access for a user who no longer requires it":
        condition = {
            "target": "User",
            "condition": "User no longer requires Access",
            "condition_subject": "User",
            "condition_predicate": "requires",
            "condition_object": "Access",
            "condition_polarity": "negative",
            "condition_temporality": "no_longer",
        }
        return _alternatives(clean, "deprovisioning-action", [
            _relation("UserDeprovisioning", "disables", "Access", **condition),
            _relation("UserDeprovisioning", "removes", "Access", **condition),
        ])

    if lower == "access certification confirms that access remains appropriate":
        return [
            _relation(
                "AccessCertification", "confirms_appropriateness_of", "Access",
                state="remains_appropriate",
            ),
            _relation(
                "Access", "remains", "Appropriate", context="AccessCertification",
                relation_role="confirmed_content",
            ),
        ]

    if lower == "a joiner process creates access for a new employee":
        return [
            _relation(
                "JoinerProcess", "creates", "Access", target="Employee",
                qualifier="new", qualifier_target="Employee",
            )
        ]

    if lower == "a mover process changes access when a person changes role":
        return [
            _relation(
                "MoverProcess", "changes", "Access", condition="Person changes Role",
                condition_subject="Person", condition_predicate="changes",
                condition_object="Role", condition_polarity="positive",
            )
        ]

    if lower == "a leaver process removes access when a person leaves the organization":
        return [
            _relation(
                "LeaverProcess", "removes", "Access", condition="Person leaves Organization",
                condition_subject="Person", condition_predicate="leaves",
                condition_object="Organization", condition_polarity="positive",
            )
        ]

    if lower == "a log record is a record of an event generated by a system":
        return [
            _definition("LogRecord", "Record"),
            _relation("LogRecord", "records", "Event"),
            _relation("Event", "generated_by", "System"),
        ]

    if lower == "a security alert is a notification generated when a detection rule identifies suspicious activity":
        return [
            _definition("SecurityAlert", "Notification"),
            _relation(
                "DetectionRule", "identifies", "SuspiciousActivity",
                context="SecurityAlert", relation_role="generation_condition",
                state="generated_when",
            ),
        ]

    return None


__all__ = ["extract_remediation_a2_claim_specs"]
